# Generated by Django 4.0.4 on 2022-05-15 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gns3webadmin', '0002_alter_connection_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
